### ISSUE TITLE
Upstream Package Control package name conflict with your fork

### ISSUE THREAD

**Issue by tukusejssirs** [Val95240/ProjectManager#14]
I’ve been using your fork for a few months already. Recently, Package Control on ST 4126 keeps removing your fork (installed via adding GitHub repository to Package Control) and installing the upstream fork.

Then I get the following error log:

```python
Traceback (most recent call last):
  File "/home/ts/.config/sublime-text/Installed Packages/ProjectManager.sublime-package/project_manager.py", line 713, in callback
  File "/home/ts/.config/sublime-text/Installed Packages/ProjectManager.sublime-package/project_manager.py", line 687, in run
  File "/home/ts/.config/sublime-text/Installed Packages/ProjectManager.sublime-package/project_manager.py", line 292, in display_projects
  File "/home/ts/.config/sublime-text/Installed Packages/ProjectManager.sublime-package/project_manager.py", line 329, in move_recent_projects_to_top
  File "/home/ts/.config/sublime-text/Installed Packages/ProjectManager.sublime-package/project_manager.py", line 329, in <listcomp>
  File "/home/ts/.config/sublime-text/Installed Packages/ProjectManager.sublime-package/project_manager.py", line 94, in pretty_path
```

I’d disable the upstream package, however, Package Control disables packages by their name only, not by their repository/URL, thus it disables both upstream and your fork.

I think its time to publish a new package on Package Control, mainly because the upstream developer does not want to merge your changes (unless someone breaks down your changes to individual/atomic changes).

**Comment by tukusejssirs** [comment]
As for workaround of the issue of reinstalling the upstream PM package, I could fix it only by following these steps:

1. Remove upstream PM package.
2. Install your forked PM package.

**Comment by tukusejssirs** [comment]
This might be caused by different problem, albeit related to the fact the the upstream and your package use the same name.

This issue happend to me again. This time I found in the ST logs the following stuff:

```python
...
reloading python 3.3 plugin ProjectManager.json_file
reloading python 3.3 plugin ProjectManager.project_manager
...
Package Control: Download Debug
  URL: https://api.github.com/repos/Val95240/ProjectManager
  Timeout: 30
  Resolved IP: 140.82.121.6
...
Package Control: Error downloading repository. URL error [Errno 113] No route to host downloading https://api.github.com/repos/Val95240/ProjectManager.
...
ignored packages updated to: ["ProjectManager", "Vintage"]
unloading python 3.3 plugin ProjectManager.json_file
unloading python 3.3 plugin ProjectManager.project_manager
reloading settings Packages/ProjectManager/project_manager.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
...
Package Control: Download Debug
  URL: https://codeload.github.com/randy3k/ProjectManager/zip/0.7.21
  Timeout: 30
  Resolved IP: 140.82.121.10
...
Package Control: Urllib HTTPS Debug Write
  GET /randy3k/ProjectManager/zip/0.7.21 HTTP/1.1
  Accept-Encoding: bzip2,gzip,deflate
  User-Agent: Package Control v3.4.1
  Connection: Keep-Alive
  Host: codeload.github.com
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 200 OK
  Access-Control-Allow-Origin: https://render.githubusercontent.com
  content-disposition: attachment; filename=ProjectManager-0.7.21.zip
  Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
  Content-Type: application/zip
  ETag: W/"2c2434a15e5784dac2452be5c2559924bd383437f5d14e7b7544f4cf816a26cf"
  Strict-Transport-Security: max-age=31536000
  Vary: Authorization,Accept-Encoding,Origin
  X-Content-Type-Options: nosniff
  X-Frame-Options: deny
  X-XSS-Protection: 1; mode=block
  Date: Mon, 24 Oct 2022 08:56:40 GMT
  Transfer-Encoding: chunked
  X-GitHub-Request-Id: A6F0:0E96:18AD2C:2084E4:63565348
Package Control: Urllib HTTPS Debug General
  Closing connection to codeload.github.com on port 443 after 1 request
Package Control: Skipping cache since the response is a zip file
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Download Debug
  URL: https://packagecontrol.io/submit?sublime_version=4126&version=0.7.21&sublime_platform=linux&old_version=2022.07.04.13.29.40&package=ProjectManager&package_control_version=3.4.1&operation=upgrade
  Timeout: 30
  Resolved IP: 50.116.34.243
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: Urllib HTTPS Debug General
  Re-using connection to packagecontrol.io on port 443 for request #2
Package Control: Urllib HTTPS Debug Write
  GET /submit?sublime_version=4126&version=0.7.21&sublime_platform=linux&old_version=2022.07.04.13.29.40&package=ProjectManager&package_control_version=3.4.1&operation=upgrade HTTP/1.1
  Accept-Encoding: bzip2,gzip,deflate
  User-Agent: Package Control v3.4.1
  Connection: Keep-Alive
  Host: packagecontrol.io
Package Control: Urllib HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 2 requests
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found system CA bundle at /opt/sublime_text/Lib/python3/certifi/cacert.pem (284098 bytes)
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /home/ts/.cache/sublime-text/Cache/Package Control/merged-ca-bundle.crt
  Using hostname "packagecontrol.io" for TLS SNI extension
```
